name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Generate timestamp
      id: timestamp
      run: echo "::set-output name=date::$(Get-Date -UFormat "%Y-%m-%dT%H-%M-%SZ")"

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag your-docker-username/your-image-name:latest-${{ steps.timestamp.outputs.date }}

    - name: Push the Docker image
      run: docker push your-docker-username/your-image-name:latest-${{ steps.timestamp.outputs.date }}
